# This GitHub Actions workflow triggers a JitPack build for the cbioportal-frontend repository whenever a new release is created.
# It constructs the JitPack build URL using the release tag and sends a request to initiate the build process.
name: Trigger JitPack Build on New Release

on:
  release:
    types:
      - created
      - prereleased

jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get release tag
        id: get_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Trigger JitPack Build
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          JITPACK_BUILD_URL="https://jitpack.io/com/github/cbioportal/cbioportal-frontend/$TAG/build.log"
          echo "Triggering JitPack build for $TAG"
          curl -I $JITPACK_BUILD_URL

      - name: Notify success
        run: echo "JitPack build triggered successfully."
